[colors]
[colors.primary]
background = "0x00141a"
foreground = "0x839495"

[colors.normal]
black = "0x00141a"
red = "0xdc312e"
green = "0x859900"
yellow = "0xb38600"
blue = "0x278bd3"
magenta = "0xd33682"
cyan = "0x2aa298"
white = "0xede7d4"

[colors.bright]
black = "0x586e74"
red = "0xdc312e"
green = "0x859900"
yellow = "0xb38600"
blue = "0x278bd3"
magenta = "0xd33682"
cyan = "0x2aa298"
white = "0xfdf6e2"
